# Generated by Django 5.2.7 on 2025-10-25 16:29

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
